# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ lpmsp430g2553 ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            pio-${{ runner.os }}-

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build (${{ matrix.env }})
        run: |
          pio run -e ${{ matrix.env }}
          ls -R .pio/build || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.env }}
          path: |
            .pio/build/${{ matrix.env }}/*.elf
            .pio/build/${{ matrix.env }}/*.hex
            .pio/build/${{ matrix.env }}/*.bin
          if-no-files-found: warn
